def test_loader_companies(): assert True
def test_loader_pl(): assert True
def test_loader_bs(): assert True
def test_loader_cf(): assert True
def test_loader_ratios(): assert True
def test_loader_peer_groups(): assert True
def test_loader_sectors(): assert True
def test_loader_documents(): assert True
def test_loader_analysis(): assert True
def test_loader_validation(): assert True
